apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpl-fe-onboarding
  namespace: authority01
spec:
  template:
    spec:
      volumes:
          - name: onboarding-i18n
            configMap:
              name: onboarding-i18n
          - name: onboarding-i18n-ecl
            configMap:
              name: onboarding-i18n-ecl
          - name: onboarding-i18n-eui
            configMap:
              name: onboarding-i18n-eui
          - name: simpl-shell-i18n
            configMap:
              name: simpl-shell-i18n
          - name: sap-i18n
            configMap:
              name: sap-i18n
          - name: sap-i18n-ecl
            configMap:
              name: sap-i18n-ecl
          - name: sap-i18n-eui
            configMap:
              name: sap-i18n-eui
          - name: identity-provider-i18n
            configMap:
              name: identity-provider-i18n
          - name: identity-provider-i18n-ecl
            configMap:
              name: identity-provider-i18n-ecl
          - name: identity-provider-i18n-eui
            configMap:
              name: identity-provider-i18n-eui
          - name: usersandroles-i18n
            configMap:
              name: usersandroles-i18n
          - name: usersandroles-i18n-ecl
            configMap:
              name: usersandroles-i18n-ecl
          - name: usersandroles-i18n-eui
            configMap:
              name: usersandroles-i18n-eui
          - name: participant-utility-i18n
            configMap:
              name: participant-utility-i18n
          - name: participant-utility-i18n-ecl
            configMap:
              name: participant-utility-i18n-ecl
          - name: participant-utility-i18n-eui
            configMap:
              name: participant-utility-i18n-eui
          - name: simpl-logo
            configMap:
              name: simpl-logo
      containers:
        - name: simpl-fe-onboarding
          volumeMounts:
              - name: onboarding-i18n
                mountPath: /usr/share/nginx/html/onboarding/assets/i18n/en.json
                subPath: en.json
              - name: onboarding-i18n-ecl
                mountPath: /usr/share/nginx/html/onboarding/assets/i18n-ecl/en.json
                subPath: en.json
              - name: onboarding-i18n-eui
                mountPath: /usr/share/nginx/html/onboarding/assets/i18n-eui/en.json
                subPath: en.json
              - name: simpl-shell-i18n
                mountPath: /usr/share/nginx/html/simpl-shell/assets/i18n/en.json
                subPath: en.json
              - name: sap-i18n
                mountPath: /usr/share/nginx/html/sap/assets/i18n/en.json
                subPath: en.json
              - name: sap-i18n-ecl
                mountPath: /usr/share/nginx/html/sap/assets/i18n-ecl/en.json
                subPath: en.json
              - name: sap-i18n-eui
                mountPath: /usr/share/nginx/html/sap/assets/i18n-eui/en.json
                subPath: en.json
              - name: identity-provider-i18n
                mountPath: /usr/share/nginx/html/identity-provider/assets/i18n/en.json
                subPath: en.json
              - name: identity-provider-i18n-ecl
                mountPath: /usr/share/nginx/html/identity-provider/assets/i18n-ecl/en.json
                subPath: en.json
              - name: identity-provider-i18n-eui
                mountPath: /usr/share/nginx/html/identity-provider/assets/i18n-eui/en.json
                subPath: en.json
              - name: usersandroles-i18n
                mountPath: /usr/share/nginx/html/usersandroles/assets/i18n/en.json
                subPath: en.json
              - name: usersandroles-i18n-ecl
                mountPath: /usr/share/nginx/html/usersandroles/assets/i18n-ecl/en.json
                subPath: en.json
              - name: usersandroles-i18n-eui
                mountPath: /usr/share/nginx/html/usersandroles/assets/i18n-eui/en.json
                subPath: en.json
              - name: participant-utility-i18n
                mountPath: /usr/share/nginx/html/participant-utility/assets/i18n/en.json
                subPath: en.json
              - name: participant-utility-i18n-ecl
                mountPath: /usr/share/nginx/html/participant-utility/assets/i18n-ecl/en.json
                subPath: en.json
              - name: participant-utility-i18n-eui
                mountPath: /usr/share/nginx/html/participant-utility/assets/i18n-eui/en.json
                subPath: en.json
              - name: simpl-logo
                mountPath: /usr/share/nginx/html/onboarding/assets/images/logo/simpl-logo.svg
                subPath: simpl-logo.svg
