apiVersion: batch/v1
kind: Job
metadata:
  name: patch-onboarding-i18n
  namespace: authority01
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: patch
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch deployment simpl-fe-onboarding \
                -n authority01 \
                --patch "$(cat /mnt/patch/patch.yaml)"
          volumeMounts:
            - name: patch-volume
              mountPath: /mnt/patch
      volumes:
        - name: patch-volume
          configMap:
            name: onboarding-i18n-patch
